name: "🐛 Bug Report"
description: "Submit a bug report to help us improve"
labels: [bug]
body:
  - type: textarea
    id: related-issues
    validations:
      required: true
    attributes:
      label: "📑 I have found these related issues/pull requests"
      description: "Search related issues by clicking [HERE](https://github.com/devopsforhumans/kumaone/issues)"
      placeholder: "Related to #1"
  - type: textarea
    id: description
    validations:
      required: false
    attributes:
      label: "Description"
      description: "You could also upload screenshots"
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "👟 Reproduction steps"
      description: "How do you trigger this bug? Please walk us through it step by step. Include all important details and add screenshots where appropriate"
      placeholder: "..."
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "👀 Expected behavior"
      description: "What did you think would happen?"
      placeholder: "..."
  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: "😓 Actual Behavior"
      description: "What actually happen?"
      placeholder: "..."
  - type: input
    id: kumaone-version
    attributes:
      label: "🐻 Kumaone Version"
      description: "Which version of kumaone are you running?"
      placeholder: "Ex. 0.0.1-alpha.6"
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: "💻 Operating System and Arch"
      description: "Which OS is your server/device running on?"
      placeholder: "Ex. Ubuntu 20.04 x64 "
    validations:
      required: true
  - type: textarea
    id: deployment-info
    attributes:
      label: "🖥️ Deployment Environment"
      description: |
        examples:
          - **Python**: python 3.9/python 3.10/python 3.11
          - **Pipenv**: pipenv version
      value: |
        - Python:
        - Pipenv:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "📝 Relevant log output"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
