---
notifications:
  - opsgenie:
      name: "Opsgenie Nofification"
      type: "Opsgenie"
      is_default: false
      apply_existing: false
      opsgeniePriority: 1
      opsgenieRegion: "eu" # us(default)/eu
      opsgenieApiKey: "something"
  - rocketchat:
      name: "RocketChat Notification"
      type: "rocket.chat"
      is_default: false
      apply_existing: false
      rocketwebhookURL: "https://chat.homelab.do"
      rocketiconemo: "rocket"
      rocketusername: "bot"
      rocketchannel: "somechannel"
  - slack:
      name: "Uptime slack notification"
      type: "slack"
      is_default: false
      apply_existing: false
      slackwebhookURL: "https://some.slack.com"
      slackiconemo: "slack"
      slackusername: "dalwar23"
      slackchannel: "uptime"
      slackchannelnotify: ""
  - teams:
      name: "Uptime teams notification"
      type: "teams"
      is_default: false
      apply_existing: false
      webhookUrl: "https://teams.microsoft.com/somehting/"
  - webhook:
      name: "Uptime webhook notification"
      type: "webhook"
      is_default: false
      apply_existing: false
      webhookURL: "https://custom.webhookurl.homelab"
      webhookAdditionalHeaders: ""
      webhookCustomBody: "this is a webhook message"
      webhookContentType: "application/json"
