name: kumaone python package

on:
  push:
    branches:
      - main
      - feat/dh-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install pipenv
        run: pip install pipenv wheel
      - name: Install dependencies
        run: pipenv install --dev
      - name: Build kumaone python package
        run: pipenv run hatch build
      - name: Install kumaone package
        run: pipenv install --ignore-pipfile .
      - name: Check kumaone version
        run: pipenv run kumaone info
